"""adding role atribute

Revision ID: 51468cb447d2
Revises: 2b48c2097803
Create Date: 2023-09-13 19:47:28.183685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51468cb447d2'
down_revision = '2b48c2097803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), server_default='user', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
