"""add image_name and image_path

Revision ID: c44c903fa1a6
Revises: 51468cb447d2
Create Date: 2024-04-20 17:16:59.591078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44c903fa1a6'
down_revision = '51468cb447d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
